-- 资产基础信息主表(资产清查汇总表)
CREATE TABLE `asset_base_info` (
  `id` bigint NOT NULL COMMENT '业务主键（流水号，系统自动生成）',
  `dept_no` varchar(50) NOT NULL DEFAULT '' COMMENT '组织机构编码',
  `responsible_unit` varchar(255) NOT NULL DEFAULT '' COMMENT '填报单位',
  `responsible_person` varchar(50) NOT NULL DEFAULT '' COMMENT '单位负责人',
  `informant` varchar(50) NOT NULL DEFAULT '' COMMENT '填报人',
  `informant_phone` varchar(50) NOT NULL DEFAULT '' COMMENT '填报人联系方式',
  `auditor` varchar(50) DEFAULT '' COMMENT '数据复核人（二三级单位需填写）',
  `auditor_phone` varchar(50) DEFAULT '' COMMENT '数据复核人联系方式',
  `asset_code` varchar(64) NOT NULL COMMENT '资产编号，系统唯一标识，必填',
  `internal_asset_code` varchar(64) COMMENT '企业内部资产编号，非必填',
  `asset_name` varchar(500) NOT NULL COMMENT '资产名称，必填',
  `group_name` varchar(100) NOT NULL DEFAULT '' COMMENT '所属集团名称，必填',
  `property_unit_no` varchar(100) COMMENT '产权单位编码',
  `property_unit` varchar(200) DEFAULT '' COMMENT '产权单位名称，在扩展表中填写',
  `asset_type` varchar(50) NOT NULL DEFAULT '' COMMENT '资产分类（分类字典表），必填',
  `asset_type_code` varchar(20) NOT NULL DEFAULT '' COMMENT '资产分类（分类字典表）code',
  `certificate_status` varchar(50) COMMENT '权证情况（房产证和土地证，仅房产证，仅土地证，不动产权证，无证），房屋土地的必填',
  `region_code` varchar(50) NOT NULL DEFAULT '' COMMENT '区域编码（到区县），必填',
  `region_name` varchar(100) NOT NULL DEFAULT '' COMMENT '行政区域，必填',
  `asset_location` varchar(500) NOT NULL DEFAULT '' COMMENT '资产位置（详细地址），必填',
  `inventory_date` date COMMENT '清查基准日',
  `usage_status` json COMMENT '资产使用状态（自用，出租，闲置，其他（出借、被占用、委托管理等）），必填',
  `usage_status_remark` text COMMENT '资产使用状态备注，为其他时必填',
  `quantity` int COMMENT '总-数量（套/栋/宗/项等）',
  `land_area` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '土地面积（平方米）',
  `building_area` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '建筑面积（平方米）',
  `mileage` decimal(20,2) COMMENT '里程（千米）',
  `original_value` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '原值（万元），必填',
  `accumulated_depreciation` decimal(20,2) COMMENT '累计折旧/摊销（万元）',
  `net_value` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '净值（万元），必填',
  `estimated_value` decimal(20,2) COMMENT '估值（万元）',
  `self_quantity` int COMMENT '自用-数量（套/栋/宗/项等）',
  `self_land_area` decimal(20,2) COMMENT '自用-土地面积（平方米）',
  `self_building_area` decimal(20,2) COMMENT '自用-建筑面积（平方米）',
  `self_original_value` decimal(20,2) COMMENT '自用-原值（万元）',
  `self_mileage` decimal(20,2) COMMENT '自用-里程（千米）',
  `self_accumulated_depreciation` decimal(20,2) COMMENT '自用-累计折旧/摊销（万元）',
  `self_net_value` decimal(20,2) COMMENT '自用-净值（万元）',
  `self_estimated_value` decimal(20,2) COMMENT '自用-估值（万元）',
  `rent_quantity` int COMMENT '出租-数量（套/栋/宗/项等）',
  `rent_land_area` decimal(20,2) COMMENT '出租-土地面积（平方米）',
  `rent_building_area` decimal(20,2) COMMENT '出租-建筑面积（平方米）',
  `rent_original_value` decimal(20,2) COMMENT '出租-原值（万元）',
  `rent_mileage` decimal(20,2) COMMENT '出租-里程（千米）',
  `rent_accumulated_depreciation` decimal(20,2) COMMENT '出租-累计折旧/摊销（万元）',
  `rent_net_value` decimal(20,2) COMMENT '出租-净值（万元）',
  `rent_estimated_value` decimal(20,2) COMMENT '出租-估值（万元）',
  `idle_quantity` int COMMENT '闲置-数量（套/栋/宗/项等）',
  `idle_land_area` decimal(20,2) COMMENT '闲置-土地面积（平方米）',
  `idle_building_area` decimal(20,2) COMMENT '闲置-建筑面积（平方米）',
  `idle_original_value` decimal(20,2) COMMENT '闲置-原值（万元）',
  `idle_mileage` decimal(20,2) COMMENT '闲置-里程（千米）',
  `idle_accumulated_depreciation` decimal(20,2) COMMENT '闲置-累计折旧/摊销（万元）',
  `idle_net_value` decimal(20,2) COMMENT '闲置-净值（万元）',
  `idle_estimated_value` decimal(20,2) COMMENT '闲置-估值（万元）',
  `other_quantity` int COMMENT '其他-数量（套/栋/宗/项等）',
  `other_land_area` decimal(20,2) COMMENT '其他-土地面积（平方米）',
  `other_building_area` decimal(20,2) COMMENT '其他-建筑面积（平方米）',
  `other_original_value` decimal(20,2) COMMENT '其他-原值（万元）',
  `other_mileage` decimal(20,2) COMMENT '其他-里程（千米）',
  `other_accumulated_depreciation` decimal(20,2) COMMENT '其他-累计折旧/摊销（万元）',
  `other_net_value` decimal(20,2) COMMENT '其他-净值（万元）',
  `other_estimated_value` decimal(20,2) COMMENT '其他-估值（万元）',
  `status` varchar(50) NOT NULL DEFAULT '' COMMENT '流程状态(默认草稿，待提交，审核中、已入库、已取消、已删除)',
  `submit_user` bigint COMMENT '流程提交人',
  `process_instance_id` varchar(64) NOT NULL DEFAULT '' COMMENT '流程ID',
  `version` int NOT NULL DEFAULT '1' COMMENT '版本号',
  `dept_ids` json COMMENT '部门权限ID',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT 'b'0'' COMMENT '是否删除（0-否，1-是）',
  `is_draft` bit(1) NOT NULL DEFAULT 'b'1'' COMMENT '是否为草稿（1-是，0-否）',
  `deleted_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '删除理由，删除时必填',
  `is_sys_push` bit(1) NOT NULL DEFAULT 'b'0'' COMMENT '是否系统推送数据（0-否，1-是）',
  `longitude` varchar(30) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(30) NOT NULL DEFAULT '' COMMENT '纬度',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_base_asset_code` (`asset_code`, `deleted`, `is_draft`),
  KEY `idx_base_asset_name` (`asset_name`),
  KEY `idx_base_dept_no` (`dept_no`),
  KEY `idx_base_region_code` (`region_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产基础信息主表(资产清查汇总表)';
