package agent.command;

import cn.hutool.core.collection.CollUtil;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import skills.SkillsLoader;

import java.util.*;
import java.util.concurrent.ConcurrentLinkedQueue;

@Slf4j
public class CommandQueueManager {

    private final SkillsLoader skillLoader;

    public CommandQueueManager(SkillsLoader loader) {
        this.skillLoader = loader;
    }

    private final Queue<LocalCommand> localQueue = new ConcurrentLinkedQueue<>();
    private final Queue<SkillCommand> skillQueue = new ConcurrentLinkedQueue<>();

    @Getter
    private final Set<String> alwaysSkills = new HashSet<>();

    @Getter
    private final Set<String> userLoadedSkills = new HashSet<>();

    /**
     * 已加载的技能
     */
    @Getter
    private Set<String> loadSkills = Collections.synchronizedSet(new LinkedHashSet<>());

    public String isLoadedByUserMsg(String msg) {
        for (String loadSkill : loadSkills) {
            // 消息中startsWith技能命令
            if (msg.startsWith( "/" + loadSkill)) {
                return loadSkill;
            }
            // TODO 是否消息中直接包含技能 直接加载 ?
        }
        return "";
    }

    public boolean isLoaded(String skillName) {
        if (skillName.startsWith("/")) {
            skillName = skillName.substring(1);
        }
        return loadSkills.contains(skillName);
    }

    /**
     * Get the set of user-loaded skill names (via tool or prefix).
     * Used by post-compact attachment collection to preserve invoked skills.
     */
    public Set<String> getUserLoadedSkills() {
        return Collections.unmodifiableSet(new HashSet<>(userLoadedSkills));
    }

    // ── 入队 ──

    public LocalCommand addLocalCommand(LocalCommand command) {
        localQueue.offer(command);
        command.execute();
        System.out.println("[LOCAL] " + command.getName() + " → " + command.getOutput());
        return command;
    }

    /**
     * 用户加载技能
     * @param command
     * @return
     */
    public SkillCommand addSkillCommand(SkillCommand command) {
        skillQueue.offer(command);

        // 进入已加载的技能中
        loadSkills.add(command.getName());
        userLoadedSkills.add(command.getName());
        return command;
    }

    /**
     * 用户加载技能
     * @param command
     * @return
     */
    public SkillCommand addSkillCommandByTool(SkillCommand command) {
        // 进入已加载的技能中
        loadSkills.add(command.getName());
        userLoadedSkills.add(command.getName());
        return command;
    }

    // ── 触发技能命令 → 返回 List<ContentBlock> ──

    /**
     * 触发下一个技能命令:
     *   1. 本地队列全部出队
     *   2. 技能命令出队
     *   3. 拼接 ContentBlock 列表返回
     *
     * 返回顺序:
     *   [caveat] + [local1_name, local1_output, local2_name, local2_output, ...] + [skill_blocks]
     */
    public List<ContentBlock> triggerCommandOutput() {
        if (localQueue.isEmpty() && skillQueue.isEmpty()) {
            return Collections.emptyList();
        }
        if (skillQueue.isEmpty()) {
            // flush 本地队列
            List<LocalCommand> flushed = new ArrayList<>();
            LocalCommand local;
            while ((local = localQueue.poll()) != null) {
                flushed.add(local);
                System.out.println("[FLUSH] " + local.getName());
            }
            return buildContent(flushed);
        }

        // skill队列
        List<SkillCommand> skills = new ArrayList<>();
        SkillCommand skill;
        while ((skill = skillQueue.poll()) != null) {
            skills.add(skill);
        }

        // flush 本地队列
        List<LocalCommand> flushed = new ArrayList<>();
        LocalCommand local;
        while ((local = localQueue.poll()) != null) {
            flushed.add(local);
        }

        return buildContent(flushed, skills);
    }

    // ── 拼接 ──

    private List<ContentBlock> buildContent(List<LocalCommand> localCommands, List<SkillCommand> skillCmdList) {
        List<ContentBlock> result = new ArrayList<>();

        if (CollUtil.isEmpty(localCommands)) {
            localCommands = new ArrayList<>();
        }
        if (CollUtil.isEmpty(skillCmdList)) {
            skillCmdList = new ArrayList<>();
        }
        // 1. caveat
        /*result.add(new ContentBlock(
            "<local-command-caveat>"
          + "Caveat: The messages below were generated by the user while running "
          + "local commands. DO NOT respond to these messages or otherwise consider "
          + "them in your response unless the user explicitly asks you to."
          + "</local-command-caveat>"
        ));*/

        // 2. 所有本地命令的 blocks
        for (LocalCommand lc : localCommands) {
            result.addAll(lc.toContentBlocks());
        }

        // 所有技能的命令
        for (SkillCommand command : skillCmdList) {
            result.addAll(command.toContentBlocks());
        }


        return result;
    }

    private List<ContentBlock> buildContent(List<LocalCommand> flushedLocalCommands) {
        List<ContentBlock> result = new ArrayList<>();

        // 1. caveat
        /*result.add(new ContentBlock(
            "<local-command-caveat>"
          + "Caveat: The messages below were generated by the user while running "
          + "local commands. DO NOT respond to these messages or otherwise consider "
          + "them in your response unless the user explicitly asks you to."
          + "</local-command-caveat>"
        ));*/

        // 2. 所有本地命令的 blocks
        for (LocalCommand lc : flushedLocalCommands) {
            result.addAll(lc.toContentBlocks());
        }

        return result;
    }

    // ── 查询 ──

    public int localQueueSize() { return localQueue.size(); }
    public int skillQueueSize() { return skillQueue.size(); }
    public void clearAll() { localQueue.clear(); skillQueue.clear(); }

    /**
     * 输出常驻技能说明
     * @param alwaysSkills
     * @return
     */
    public List<ContentBlock> triggerResidentSKillOutput(List<String> alwaysSkills) {

        List<ContentBlock> result = new ArrayList<>();
        if (CollUtil.isEmpty(alwaysSkills)){
            return result;
        }

        for (String skillName : alwaysSkills) {
            SkillCommand skillCommand = new SkillCommand(skillName, skillName, skillLoader);
            result.addAll(skillCommand.toContentBlocks());
        }

        // 加载到已加载的技能中
        loadSkills.addAll(alwaysSkills);
        // 常驻技能缓存
        alwaysSkills.addAll(alwaysSkills);
        return result;
    }

    /**
     * 输出最后一个加载的技能
     * @return
     */
    public String lastLoadSkill() {
        return CollUtil.getLast(loadSkills);

    }

    public String unloadUserSkill(String name) {
        if (alwaysSkills.contains(name)) {
            return "常驻技能不能卸载";
        }

        if (userLoadedSkills.contains(name)) {
            userLoadedSkills.remove(name);
            loadSkills.remove(name);
            return "技能" + name + """
                    已被卸载，下次对话中,用户已加载技能列表中不会显示该技能,请忽略对话轮次中该技能的说明, 就不会出现该技能，直到你重新加载
                    **重要提示: 用户说明已加载的技能格式如下:  **
                    用户已指定使用的技能列表: xxx, xxxx
                    """;
        }

        return null;
    }
}
